version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "austenstone"
    assignees:
      - "austenstone"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "austenstone"
    assignees:
      - "austenstone"
