name: Autofix Code Scanning Alerts
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - run: npx ghas-fixer -y -o ${GITHUB_ORG} -r ${GITHUB_REPOSITORY}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.event.repository.name }}
          GITHUB_ORG: ${{ github.repository_owner }}